-- Profiles Table
CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  weight DECIMAL(5, 2), -- kg
  height DECIMAL(5, 2), -- cm
  age INT,
  gender TEXT CHECK (gender IN ('male', 'female', 'other')),
  activity_level TEXT CHECK (activity_level IN ('sedentary', 'lightly_active', 'moderately_active', 'very_active', 'extra_active')),
  goal TEXT CHECK (goal IN ('weight_loss', 'maintenance', 'cut', 'bulk')) DEFAULT 'maintenance',
  tdee INT, -- Estimated Daily Total Energy Expenditure
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Calorie Logs Table
CREATE TABLE calorie_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  food_name TEXT NOT NULL,
  calories DECIMAL(7, 2) NOT NULL,
  protein DECIMAL(5, 2),
  fat DECIMAL(5, 2),
  carbs DECIMAL(5, 2),
  sugar DECIMAL(5, 2),
  sodium DECIMAL(7, 2),
  cholesterol DECIMAL(7, 2),
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE calorie_logs ENABLE ROW LEVEL SECURITY;

-- Policies for Profiles (Using id instead of user_id)
CREATE POLICY "Users can view their own profiles" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profiles" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert their own profiles" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Policies for Calorie Logs
CREATE POLICY "Users can view their own calorie logs" ON calorie_logs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own calorie logs" ON calorie_logs FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own calorie logs" ON calorie_logs FOR DELETE USING (auth.uid() = user_id);

-- Storage Bucket Setup
-- 1. Create Bucket
INSERT INTO storage.buckets (id, name, public) 
VALUES ('food-images', 'food-images', false);

-- 2. Storage RLS Policies (Ensure users only access their own folder)
-- Folder structure: food-images/{user_id}/{filename}

CREATE POLICY "Allow users to upload food images"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'food-images' AND 
  (storage.foldername(name))[1] = auth.uid()::text
);

CREATE POLICY "Allow users to view their own food images"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'food-images' AND 
  (storage.foldername(name))[1] = auth.uid()::text
);

CREATE POLICY "Allow users to delete their own food images"
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id = 'food-images' AND 
  (storage.foldername(name))[1] = auth.uid()::text
);

-- =========================================================================
-- MIGRATION: Add gamification columns to the profiles table
-- Run this SQL in your Supabase SQL Editor to support the gamification features
-- =========================================================================

ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS points INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS streak INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS custom_rewards JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS redeemed_history JSONB DEFAULT '[]'::jsonb;

-- Optional cleanup: Drop the old workout_history column from profiles if it exists
ALTER TABLE profiles DROP COLUMN IF EXISTS workout_history;

-- =========================================================================
-- MIGRATION: Add workout_records table for relational workout logging
-- Run this SQL in your Supabase SQL Editor
-- =========================================================================

CREATE TABLE IF NOT EXISTS workout_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  date TEXT NOT NULL, -- YYYY-MM-DD
  gym BOOLEAN DEFAULT false,
  walk BOOLEAN DEFAULT false,
  steps10k BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, date)
);

-- Enable RLS
ALTER TABLE workout_records ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view their own workout records" ON workout_records FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own workout records" ON workout_records FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own workout records" ON workout_records FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own workout records" ON workout_records FOR DELETE USING (auth.uid() = user_id);


